#!/usr/bin/env bash
#-------------------------------------------------------------------------------
# project name:  Boxcycler Builds
# file name:     build
# author:        Steve Vasta
# created:       May 31, 2018
# modified:      July 19, 2018
# description:   A simple file to kick off a packer build using
#                VMware as a hypervisor . . .

set -o errexit -o nounset -o pipefail

if [ "${DEBUG:=false}" = "true" ]; then
  set -o xtrace
fi

#  packer build -debug -only="vmware-iso" $1
  packer build -only="vmware-iso" $1
