#!/usr/bin/env bash
#-------------------------------------------------------------------------------
# project name:  Boxcycler Builds
# file name:     build
# author:        Steve Vasta
# created:       May 31, 2018
# modified:      July 25, 2018
# description:   A simple file to kick off a packer build using
#                Oracle VirtualBox as a hypervisor . . .

set -o errexit -o nounset -o pipefail

if [ "${DEBUG:=false}" = "true" ]; then
  set -o xtrace
fi

if [ -d packer_cache ]; then
  rm -rf packer_cache
fi

MODARG=${1/.json//}
if [ -d output-centos${MODARG}-virtualbox-iso ]; then
  rm -rf output-centos${MODARG}-virtualbox-iso
fi

version=$(cat VERSION)
if [ ! -v MICROSOFTLINUX ]; then
#  packer build -debug -only="virtualbox-iso" $1
  packer build -var "version=${version}" $1
else
  MODARG=${1/.json/-win.json}
  powershell.exe "packer build -only=\"virtualbox-ovf\" $MODARG"
fi
