#!/usr/bin/env bash
#-------------------------------------------------------------------------------
# project name:  Boxcycler Builds
# file name:     build
# author:        Steve Vasta
# created:       May 31, 2018
# modified:      July 19, 2018
# description:   A simple file to kick off a packer build using
#                Oracle VirtualBox as a hypervisor . . .

set -o errexit -o nounset -o pipefail

if [ "${DEBUG:=false}" = "true" ]; then
  set -o xtrace
fi

if [ ! -v MICROSOFTLINUX ]; then
  packer build -only="virtualbox-iso" $1
else
  MODARG=${1/.json/-win.json}
  powershell.exe "packer build -only=\"virtualbox-iso\" $MODARG"
fi
